name: Deploy Mango Media Website

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: infrastructure/package-lock.json
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Install CDK dependencies
      working-directory: infrastructure
      run: npm ci
      
    - name: Build CDK project
      working-directory: infrastructure
      run: npm run build
      
    - name: Clean up CDK output directories
      run: rm -rf cdk-out infrastructure/cdk.out
      
    - name: Bootstrap CDK (if needed)
      run: npx cdk bootstrap --require-approval never --app "infrastructure/bin/infrastructure.js"
      
    - name: Synthesize CDK templates
      run: npx cdk synth --app "infrastructure/bin/infrastructure.js" --output cdk-out
      
    - name: Deploy infrastructure with CloudFormation
      run: |
        aws cloudformation deploy \
          --template-file cdk-out/InfrastructureStack.template.json \
          --stack-name InfrastructureStack \
          --capabilities CAPABILITY_IAM \
          --no-fail-on-empty-changeset
      
    - name: Get stack outputs
      id: stack-outputs
      run: |
        BUCKET_NAME=$(aws cloudformation describe-stacks --stack-name InfrastructureStack --query 'Stacks[0].Outputs[?OutputKey==`BucketName`].OutputValue' --output text)
        DISTRIBUTION_ID=$(aws cloudformation describe-stacks --stack-name InfrastructureStack --query 'Stacks[0].Outputs[?OutputKey==`DistributionId`].OutputValue' --output text)
        echo "bucket-name=$BUCKET_NAME" >> $GITHUB_OUTPUT
        echo "distribution-id=$DISTRIBUTION_ID" >> $GITHUB_OUTPUT
        
    - name: Deploy website files to S3
      run: |
        aws s3 sync . s3://${{ steps.stack-outputs.outputs.bucket-name }} \
          --delete \
          --exclude "infrastructure/*" \
          --exclude ".git/*" \
          --exclude ".github/*" \
          --exclude "node_modules/*" \
          --exclude "*.md" \
          --exclude ".*" \
          --exclude "cdk-outputs.json"
          
    - name: Invalidate CloudFront cache
      run: |
        aws cloudfront create-invalidation \
          --distribution-id ${{ steps.stack-outputs.outputs.distribution-id }} \
          --paths "/*"