name: Deploy Website Files Only

on:
  push:
    branches: [ main ]
    paths: 
      - 'index.html'
      - 'styles.css'
      - '*.jpeg'
      - '*.jpg'
      - '*.png'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Deploy website files to S3
      run: |
        echo "Uploading website files to S3..."
        aws s3 sync . s3://mangomedia-website-simple \
          --delete \
          --exclude "*" \
          --include "index.html" \
          --include "styles.css" \
          --include "*.jpeg" \
          --include "*.jpg" \
          --include "*.png"
        echo "✅ Files uploaded successfully"
        
    - name: Invalidate CloudFront cache
      run: |
        echo "Creating CloudFront invalidation..."
        INVALIDATION_ID=$(aws cloudfront create-invalidation \
          --distribution-id E1V511OTCBNCML \
          --paths "/*" \
          --query 'Invalidation.Id' \
          --output text)
        echo "✅ Invalidation created: $INVALIDATION_ID"
        echo "🌐 Website will update in 1-5 minutes"
        
    - name: Display success message
      run: |
        echo "🎉 Deployment completed successfully!"
        echo "📝 Changes will be live at https://mangomedia.com in 1-5 minutes"
        echo "🔄 CloudFront is invalidating the cache globally"